Implement %ASA-3-114019
NCATComp410/comp410_spring_2021 pull request #30
Opened 2021-02-17 20:42 UTC by ereewa3

2021-02-17 20:44 UTC, ereewa3 commented
#30

2021-02-18 01:50 UTC, claesmk requested changes
It looks like you are merging your version of demo.py which is going to remove everyone else's slogans. 

Also, there are only spacing changes in test_log_parse.py.

2021-02-18 03:12 UTC, ereewa3 commented
How does it look now?

2021-02-18 12:10 UTC, claesmk commented
> How does it look now?

I don't see any code to implement %ASA-3-114019.  I also looked in your fork but don't see the code there either.  Does it work OK on your development system?  Maybe something wasn't checked-in?

2021-02-18 14:10 UTC, ereewa3 commented
#22

2021-02-18 21:34 UTC, ereewa3 commented
Corrected now.

2021-02-18 23:44 UTC, claesmk commented
Please see the review comments above I don't see the changes that address these

2021-02-19 01:08 UTC, claesmk approved these changes

2021-02-19 01:08 UTC, claesmk commented on id_pkg/src/log_parse.py
> +
It looks like you added extra space here.  Was this on purpose?  It would be better not to add this because it will create merge conflicts for someone

2021-02-19 01:08 UTC, claesmk commented on id_pkg/test/test_log_parse.py
> +
Also extra space here

2021-02-19 01:08 UTC, claesmk commented on id_pkg/test/test_log_parse.py
> +        #%ASA-3-114019: Failed to set media type in 4GE SSM I/O card (error error_string)
This looks good

2021-02-19 01:08 UTC, claesmk commented on id_pkg/src/log_parse.py
> +        if id == 114019:
This is OK and will work but as I commented in some other reviews it could be improved like this:
```
match = re.search(r'\(error (\w+)\)', df.loc[id, 'Text'])
```

2021-02-19 01:08 UTC, merged